---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: helper-pipeline
spec:
  params:
    - name: dev-region
      description: the target region
    - name: dev-resource-group
      description: Resource Group

  workspaces:
    - name: artifacts

  tasks:
    - name: test-run
      taskRef:
        name: ciso-image-sign
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: region
          value: $(params.dev-region)
        - name: resource-group
          value: $(params.dev-resource-group)
